"""Your migration message

Revision ID: e54adad95814
Revises: 
Create Date: 2024-02-05 18:22:53.843899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e54adad95814'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actor')
    with op.batch_alter_table('film_text', schema=None) as batch_op:
        batch_op.drop_index('idx_title_description', mysql_prefix='FULLTEXT')

    op.drop_table('film_text')
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_index('idx_fk_address_id')
        batch_op.drop_index('idx_unique_manager')

    op.drop_table('store')
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_index('idx_fk_city_id')
        batch_op.drop_index('idx_location', mysql_prefix='SPATIAL')

    op.drop_table('address')
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_index('idx_fk_country_id')

    op.drop_table('city')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index('idx_fk_customer_id')
        batch_op.drop_index('idx_fk_staff_id')

    op.drop_table('payment')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index('idx_fk_address_id')
        batch_op.drop_index('idx_fk_store_id')

    op.drop_table('staff')
    op.drop_table('film_category')
    op.drop_table('language')
    with op.batch_alter_table('film_actor', schema=None) as batch_op:
        batch_op.drop_index('idx_fk_film_id')

    op.drop_table('film_actor')
    op.drop_table('category')
    op.drop_table('country')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=mysql.SMALLINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index('idx_fk_address_id')
        batch_op.drop_index('idx_fk_store_id')
        batch_op.drop_index('idx_last_name')
        batch_op.drop_constraint('fk_customer_address', type_='foreignkey')
        batch_op.drop_constraint('fk_customer_store', type_='foreignkey')
        batch_op.drop_column('store_id')
        batch_op.drop_column('last_name')
        batch_op.drop_column('address_id')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_update')
        batch_op.drop_column('create_date')
        batch_op.drop_column('active')
        batch_op.drop_column('email')

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.alter_column('film_id',
               existing_type=mysql.SMALLINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('release_year',
               existing_type=mysql.YEAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('rating',
               existing_type=mysql.ENUM('G', 'PG', 'PG-13', 'R', 'NC-17'),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'G'"))
        batch_op.alter_column('special_features',
               existing_type=mysql.SET('Trailers', 'Commentaries', 'Deleted Scenes', 'Behind the Scenes'),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index('idx_fk_language_id')
        batch_op.drop_index('idx_fk_original_language_id')
        batch_op.drop_index('idx_title')
        batch_op.drop_constraint('fk_film_language_original', type_='foreignkey')
        batch_op.drop_constraint('fk_film_language', type_='foreignkey')
        batch_op.drop_column('language_id')
        batch_op.drop_column('rental_duration')
        batch_op.drop_column('rental_rate')
        batch_op.drop_column('last_update')
        batch_op.drop_column('length')
        batch_op.drop_column('replacement_cost')
        batch_op.drop_column('original_language_id')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_copies', sa.Integer(), nullable=True))
        batch_op.alter_column('inventory_id',
               existing_type=mysql.MEDIUMINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('film_id',
               existing_type=mysql.SMALLINT(unsigned=True),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_index('idx_fk_film_id')
        batch_op.drop_index('idx_store_id_film_id')
        batch_op.drop_constraint('fk_inventory_store', type_='foreignkey')
        batch_op.drop_constraint('fk_inventory_film', type_='foreignkey')
        batch_op.create_foreign_key(None, 'film', ['film_id'], ['film_id'])
        batch_op.drop_column('last_update')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.alter_column('rental_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('inventory_id',
               existing_type=mysql.MEDIUMINT(unsigned=True),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=mysql.SMALLINT(unsigned=True),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_index('idx_fk_customer_id')
        batch_op.drop_index('idx_fk_inventory_id')
        batch_op.drop_index('idx_fk_staff_id')
        batch_op.drop_index('rental_date')
        batch_op.drop_constraint('fk_rental_staff', type_='foreignkey')
        batch_op.drop_constraint('fk_rental_customer', type_='foreignkey')
        batch_op.drop_constraint('fk_rental_inventory', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['customer_id'])
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['inventory_id'])
        batch_op.drop_column('staff_id')
        batch_op.drop_column('last_update')
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('staff_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_rental_inventory', 'inventory', ['inventory_id'], ['inventory_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_rental_customer', 'customer', ['customer_id'], ['customer_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_rental_staff', 'staff', ['staff_id'], ['staff_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index('rental_date', ['rental_date', 'inventory_id', 'customer_id'], unique=True)
        batch_op.create_index('idx_fk_staff_id', ['staff_id'], unique=False)
        batch_op.create_index('idx_fk_inventory_id', ['inventory_id'], unique=False)
        batch_op.create_index('idx_fk_customer_id', ['customer_id'], unique=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(unsigned=True),
               nullable=False)
        batch_op.alter_column('inventory_id',
               existing_type=sa.Integer(),
               type_=mysql.MEDIUMINT(unsigned=True),
               nullable=False)
        batch_op.alter_column('rental_date',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_inventory_film', 'film', ['film_id'], ['film_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_inventory_store', 'store', ['store_id'], ['store_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index('idx_store_id_film_id', ['store_id', 'film_id'], unique=False)
        batch_op.create_index('idx_fk_film_id', ['film_id'], unique=False)
        batch_op.alter_column('film_id',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(unsigned=True),
               nullable=False)
        batch_op.alter_column('inventory_id',
               existing_type=sa.Integer(),
               type_=mysql.MEDIUMINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('available_copies')

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_language_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('replacement_cost', mysql.DECIMAL(precision=5, scale=2), server_default=sa.text("'19.99'"), nullable=False))
        batch_op.add_column(sa.Column('length', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('rental_rate', mysql.DECIMAL(precision=4, scale=2), server_default=sa.text("'4.99'"), nullable=False))
        batch_op.add_column(sa.Column('rental_duration', mysql.TINYINT(unsigned=True), server_default=sa.text("'3'"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('language_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_film_language', 'language', ['language_id'], ['language_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_film_language_original', 'language', ['original_language_id'], ['language_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index('idx_title', ['title'], unique=False)
        batch_op.create_index('idx_fk_original_language_id', ['original_language_id'], unique=False)
        batch_op.create_index('idx_fk_language_id', ['language_id'], unique=False)
        batch_op.alter_column('special_features',
               existing_type=sa.String(length=255),
               type_=mysql.SET('Trailers', 'Commentaries', 'Deleted Scenes', 'Behind the Scenes'),
               existing_nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('G', 'PG', 'PG-13', 'R', 'NC-17'),
               existing_nullable=True,
               existing_server_default=sa.text("'G'"))
        batch_op.alter_column('release_year',
               existing_type=sa.Integer(),
               type_=mysql.YEAR(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('film_id',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('create_date', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=45), nullable=False))
        batch_op.add_column(sa.Column('address_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=45), nullable=False))
        batch_op.add_column(sa.Column('store_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_customer_store', 'store', ['store_id'], ['store_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_customer_address', 'address', ['address_id'], ['address_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index('idx_last_name', ['last_name'], unique=False)
        batch_op.create_index('idx_fk_store_id', ['store_id'], unique=False)
        batch_op.create_index('idx_fk_address_id', ['address_id'], unique=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('country',
    sa.Column('country_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('country', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('country_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('category',
    sa.Column('category_id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('film_actor',
    sa.Column('actor_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('film_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], name='fk_film_actor_actor', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['film_id'], ['film.film_id'], name='fk_film_actor_film', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('actor_id', 'film_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('film_actor', schema=None) as batch_op:
        batch_op.create_index('idx_fk_film_id', ['film_id'], unique=False)

    op.create_table('language',
    sa.Column('language_id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.CHAR(length=20), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('language_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('film_category',
    sa.Column('film_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], name='fk_film_category_category', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['film_id'], ['film.film_id'], name='fk_film_category_film', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('film_id', 'category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('staff',
    sa.Column('staff_id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('address_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('picture', sa.BLOB(), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('store_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=40), nullable=True),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], name='fk_staff_address', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], name='fk_staff_store', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('staff_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index('idx_fk_store_id', ['store_id'], unique=False)
        batch_op.create_index('idx_fk_address_id', ['address_id'], unique=False)

    op.create_table('payment',
    sa.Column('payment_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('customer_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('staff_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('rental_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('payment_date', mysql.DATETIME(), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name='fk_payment_customer', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rental_id'], ['rental.rental_id'], name='fk_payment_rental', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], name='fk_payment_staff', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('payment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index('idx_fk_staff_id', ['staff_id'], unique=False)
        batch_op.create_index('idx_fk_customer_id', ['customer_id'], unique=False)

    op.create_table('city',
    sa.Column('city_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('country_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], name='fk_city_country', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('city_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_index('idx_fk_country_id', ['country_id'], unique=False)

    op.create_table('address',
    sa.Column('address_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('district', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('city_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('postal_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('location', sa.NullType(), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], name='fk_address_city', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('address_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_index('idx_location', ['location'], unique=False, mysql_prefix='SPATIAL')
        batch_op.create_index('idx_fk_city_id', ['city_id'], unique=False)

    op.create_table('store',
    sa.Column('store_id', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('manager_staff_id', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('address_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], name='fk_store_address', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_staff_id'], ['staff.staff_id'], name='fk_store_staff', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('store_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.create_index('idx_unique_manager', ['manager_staff_id'], unique=True)
        batch_op.create_index('idx_fk_address_id', ['address_id'], unique=False)

    op.create_table('film_text',
    sa.Column('film_id', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('film_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('film_text', schema=None) as batch_op:
        batch_op.create_index('idx_title_description', ['title', 'description'], unique=False, mysql_prefix='FULLTEXT')

    op.create_table('actor',
    sa.Column('actor_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('actor_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
